version: '3.8'

services:
  mcp-task-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-task
    container_name: vibe-mcp-task
    ports:
      - "3456:3456"
    environment:
      - HOST=0.0.0.0
      - MCP_PORT=3456
      - TRANSPORT=http
      - RUST_LOG=info
      - VIBE_BACKEND_URL=http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3456/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  mcp-system-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-system
    container_name: vibe-mcp-system
    ports:
      - "3457:3457"
    environment:
      - HOST=0.0.0.0
      - MCP_PORT=3457
      - TRANSPORT=http
      - RUST_LOG=info
      - VIBE_BACKEND_URL=http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3457/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

networks:
  default:
    name: vibe-mcp-network
